### PR TITLE
fix: undefined array length maxMapSize

### LINKED ISSUE #5: Bug: undefined array length maxMapSize on mmap_windows.go
## problems
`pkg/mmap/mmap_windows.go` : undefined array length maxMapSize or missing type constraint

### PR DESCRIPTION
**Pull request by huang-jesse**
Fix https://github.com/chenjiandongx/mandodb/issues/5

### CODE REVIEW

**Comment by huang-jesse** [comment]
Fix [issue 5](https://github.com/chenjiandongx/mandodb/issues/5)

**Comment by chenjiandongx** [comment]
@huang-jesse 

Should this value be 256TB? refer to prometheus code https://github.com/prometheus/prometheus/blob/main/tsdb/fileutil/mmap_amd64.go#L19

**Comment by huang-jesse** [comment]
> @huang-jesse
> 
> Should this value be 256TB? refer to prometheus code https://github.com/prometheus/prometheus/blob/main/tsdb/fileutil/mmap_amd64.go#L19

Oh, it's a mistake, your opinion is correct. I will correct it latter.

**Comment by huang-jesse** [comment]
@chenjiandongx I've adjusted the `maxMapSize` to `256TB`.

**Pull request merged**
